
// *** /POST routes *******************

// get all posts
GET http://localhost:3000/post
content-type: application/json

###
// create a new post
POST http://localhost:3000/post
content-type: application/json

{
  "title": "Soap Title",
  "content": "Soap Content",
  "author": "63182524e0a8631983873a22"
}

###
// delete a post
DELETE http://localhost:3000/post/631b3947709d1e95e5690628
content-type: application/json

###
// update a post
PUT http://localhost:3000/post/631b37da709d1e95e569061e
content-type: application/json

{
  "title": "Yoob Title2 UPDATED",
  "content": "Yoob content2",
  "author": "63182524e0a8631983873a22",
  "date": "2021-09-09T12:55:54.147+00:00",
  "published": true
}

###
// *** /USER routes *******************

// get all users
GET http://localhost:3000/user
content-type: application/json

###
// create a new user
POST http://localhost:3000/user
content-type: application/json

{
  "username": "a@test.com",
  "password": "test"
}

###
// delete a user
DELETE http://localhost:3000/user/631b5b7b9cef2e52ace6f963
content-type: application/json

###
// update a user
PUT http://localhost:3000/user/631b472a56450886c13a1bff
content-type: application/json

{
  "username": "updated email",
  "password": "000000",
  "admin": false
}

###
// *** /ADMIN routes *******************

// get all admins
GET http://localhost:3000/admin
content-type: application/json

###
// create a new admin
POST http://localhost:3000/admin
content-type: application/json

{
  "username": "d@test.com",
  "password": "test"
}

###
// *** /COMMENT routes *******************

// get all comments - protected route
GET http://localhost:3000/comment
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4Mzk2ODIzNDgsImV4cCI6MTY2MjgzOTc2ODc0OH0.nPmn4rVnnunlidIHjNdEBhOahjEWIsix6_2Q40oZERocIT6TBVxTYhcW4MbqKW08cn8wanR3RWL_E5zQd1Jf2Hz6_cj4MEZ0lQc7hAInfK2qFBzzLHaYbI80Zgpw5N2uIVGDTn5bnR3Idpje1GXkHBGzJTbRCBxXuYiS9QphLKhaxByXkeTROQwe4muCwljpymOIb8at_uzpiTVuZQQvZx2e2KTjBYcJvWIJv77Ru7dliBdLpys-wBk4keSZuUUE-ZKV8AQPs-misfMjGyJyEximBjr_-NQi21Sf_rcBh79YhNZtBPbwAFs2jmXbROlkCxWLQQF4-qSymGS-m1VUUdbhCir8jLwLVlYSGlkNdg0gCWEKt7t45M6D2nwj0ITMhqLcrVTMjfhbQ5b2TQ2iIHHx8IPOtekhgY1mC7IQQflvzZiW-Gs6YXlVsxex6GXNZin8A9PJg4Xitwtxp_YZzVNafwYoNpYF7pUHzEIkrMl1LW-hexwlcuqNdvEWUJy3OIcyQRugfJpTmXphjx4oAuSaFNEB9FlvKmphLsGo217Xw3drt-jIJcdE2reXkEysOiP2diqLgJug1v8AqkKQvq00TPxfmnjobE9i1ZP-uscPkiWxzhRYSsaAE6TNSYqehagtCVfDlR2gpH28YCfnpK4z1lfVrWbAIgsqlRDoUGQ 

###
// create a new comment
POST http://localhost:3000/comment
content-type: application/json

{
  "content": "test comment 3",
  "author": "631bba3511d8b2dea3b18f0f",
  "post": "631b37da709d1e95e569061e"
}

###
// *** /REGISTER routes *******************

// register a new user
POST http://localhost:3000/register
content-type: application/json

{
  "username": "a@test.com",
  "password": "test"
}

### 
// *** /LOGIN routes *******************
POST http://localhost:3000/login
content-type: application/json

{
  "username": "a@test.com",
  "password": "test"
}