
// *** /POST routes *******************

// get all posts
GET http://localhost:3000/post
content-type: application/json

###
// create a new post
POST http://localhost:3000/post
content-type: application/json

{
  "title": "Soap Title",
  "content": "Soap Content",
  "author": "63182524e0a8631983873a22"
}

###
// delete a post
DELETE http://localhost:3000/post/631b3947709d1e95e5690628
content-type: application/json

###
// update a post
PUT http://localhost:3000/post/631b37da709d1e95e569061e
content-type: application/json

{
  "title": "Yoob Title2 UPDATED",
  "content": "Yoob content2",
  "author": "63182524e0a8631983873a22",
  "date": "2021-09-09T12:55:54.147+00:00",
  "published": true
}

###
// *** /USER routes *******************

// get all users
GET http://localhost:3000/user
content-type: application/json

###
// create a new user
POST http://localhost:3000/user
content-type: application/json

{
  "username": "a@test.com",
  "password": "test"
}

###
// delete a user
DELETE http://localhost:3000/user/631b5b7b9cef2e52ace6f963
content-type: application/json

###
// update a user
PUT http://localhost:3000/user/631b472a56450886c13a1bff
content-type: application/json

{
  "username": "updated email",
  "password": "000000",
  "admin": false
}

###
// *** /ADMIN routes *******************

// get all admins
GET http://localhost:3000/admin
content-type: application/json

###
// create a new admin
POST http://localhost:3000/admin
content-type: application/json

{
  "username": "d@test.com",
  "password": "test"
}

###
// *** /COMMENT routes *******************

// get all comments - protected route
GET http://localhost:3000/comment
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDIzMzI5ODAsImV4cCI6MTY2Mjg0MjQxOTM4MH0.isLDz1qqUe7-782pXaNZCX5-NMvl-jXF7DRCHwUJOnhJrAT1F57Cv8AhOYTDoSZe6WQ6wxLPku2iu6nTK5kTNuDVlKanpYgE_zC-_MHoPzGOWVQTwtDd2RCJk2Ly5P9setYo30WYK79bo06ct0eiF0AFcAaTjnFlVwF3aGUp7o9QZlARhT_s3q4Jkl7v7ckqGlakKzgu-DKZubWo8z215O1bdUrAJpOnhhgQu7mMvVuyyRbG-EDtLHSd4Lc68Tc5KCqKKMv4hJkamsbOdbBoElsWDW_Z0XnJF27Vy_XKG_H1uOVIxu0hbm4Tsg8QPTyaFVOd0ctlWi1J_CQM-9oKcXERNLnLO69veTFVTtT57oIHqsPdJO9gJ-S7X6WVNaobnce1LPC5YWO-grLzqjHud9KHLBKPiwL8_MAgQKVHsAb1PwT7n4mWnl8MxjqszWwatKYeC3K1bTohD0xRS1hNVzys23vU2xUZAd4KOus5z_E610M8o-VAYvIsE20esC18pzHvEmtUOVbuXRsm0iNv9R3DU87BXBQyKIL5sawt4P_Ra5C0TAg1xBmU7YL9q3Tvtbxs-lf7f0ImANXSPsBz5XXQIDfAIO06I3KUNPniN0pHDl_d5coFzBplkIRzfigDWFzH3_tHa_XLpTCUudvNFDid58u0QB5Za6SVaCd-Vec

###
// create a new comment - must be logged in
POST http://localhost:3000/comment
content-type: application/json
Authorization

{
  "content": "test comment 3",
  "author": "631bba3511d8b2dea3b18f0f",
  "post": "631b37da709d1e95e569061e"
}

###
// *** /REGISTER routes *******************

// register a new user
POST http://localhost:3000/register
content-type: application/json

{
  "username": "a@test.com",
  "password": "test"
}

### 
// *** /LOGIN routes *******************
POST http://localhost:3000/login
content-type: application/json

{
  "username": "a@test.com",
  "password": "test"
}