
// *** /POST routes *******************

// get all published posts
GET http://localhost:3000/post
content-type: application/json

###
// get all posts - published and unpublished
GET http://localhost:3000/post/all
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjMzNDY4Mzk5MzcsImV4cCI6MTY2MzM0NjkyNjMzN30.GdZZRTv-42pD5JLuMq2UImOfc1Udj-g7rjSHKFI0wV_BSMB_1EE6fnyOINwd9UDqIPCfjy1RYZpNkCdxiFpBD3nccgOJNwvU16MZrs7w9VKpTWIQO8M6nNyof15KS5NnxbjGHKaef80Yel0tM4d8t63IXAJKXf_q9bjnPa29HJyPHH3ou_Eki5-YoF1csGl0Jc1HMtKCDe48mWy9G3LQ7jC678XLF5tpo9HuMJBPb-uJLKitV5ViptzTDYjvTI4Qix1g2zxVVItkxN6B8odBXz9RlYpNmlp3kq9OPS5n-z7kft32nBEMDJNu5I8u0mdgp7ecXgdSVYVBNpimBInaMfUc42IT82zDU7VAq5h958H_huH5HrYt-E4Uk9NKcuUA9hwoIH249MLKimbBH6Ec9e00xArlYSiD-E4ke_JfDnmvsmGJ818xpglo_vu9uVJ4QfQtWkccP-S9EqJry6-enAdzMH_iaVIkV2dFb1IOU5-Kg4KLxf7h1ulBV4Gzw1OaXXzuFJgQ4YbzZb27wWFSI--kw4xqUOFnHVS_zir-yxBSK-Q-wsER_DgUHNpzaxGJacZBoqyNVI3zaUwP_yf6G6CFdkR_3-rz2omYXjHgQeFcFqAw8pjoorDjVy9jOOyZiI1cCPPuzv8-tS-8W1xftRKYm-ewTjYOUUoe6ebODlo

###
// get post by id
GET http://localhost:3000/post/632ab208dc7ac4f51e7b2aad
content-type: application/json

###
// create a new post
POST http://localhost:3000/post
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

{
  "title": "Balling Post",
  "content": "SOme cool content man",
  "author": "631cea3c8af151a8f8287b31"
}

###
// delete a post
DELETE http://localhost:3000/post/blablabla
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

###
// update a post
PUT http://localhost:3000/post/631b37da709d1e95e569061e
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

{
  "title": "Yoob Title2 UPDATED",
  "content": "Yoob content2",
  "author": "63182524e0a8631983873a22",
  "date": "2021-09-09T12:55:54.147+00:00",
  "published": true
}

###
// publish a post, default is unpublished
PUT http://localhost:3000/post/6322ccc1f35cbe6a83448290/publish
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

###
// *** /USER routes *******************

// get all users
GET http://localhost:3000/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

###
// create a new user
POST http://localhost:3000/user
content-type: application/json

{
  "username": "g@test.com",
  "password": "test"
}

###
// delete a user
DELETE http://localhost:3000/user/6329f65186414af4c71a8da4
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

###
// update a user
PUT http://localhost:3000/user/6320a47f1974a135ea770ac0
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

{
  "username": "e@test.com",
  "password": "test",
  "admin": true
}

###
// fetch user by id
GET http://localhost:3000/user/631cea178af151a8f8287b2f
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

###

// *** /ADMIN routes *******************

// get all admins
GET http://localhost:3000/admin
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

###
// create a new admin
POST http://localhost:3000/admin
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDY0MzM4NTcsImV4cCI6MTY2Mjg0NjUyMDI1N30.tmOKaXWVlambEG_Nc4waQAgfurLQuNeu_ffBjVY1Rvf4YUceForcFXkf011qTAAsYMkwzzmJp-RXBFk9ZH-Zd2SHJGD-K5vfjzDFrcUaoBUuA7ZjXyPjEilCG5hovar_6Zx4Xj1whbSk5ZMqKCGi-xd8N9xiesjBSCEH-gCBH6HP4Vhid9IL6ksam1LUGy5zyk6mtlfX1492cfAN0wWWqV2RC6PCC9tIkVR4_EYwYkhGFxBbzMR6_K-Tly7WtbcFmi1zSN3S9dOdKc1hwH9vn32c429OGnvsjP4tIgSZt6SY33NyYHO1PTlOULXny5lTaBcxk2DeRfdMzX-vjqcLlu8yToiYVOt9Jt9qRkXRSIyXAV4ZfliNJSGGyxGXaqlhCeUqfyKh6OEdHNH6hBa209tozp8fGRK9fiZXCgHoU5FWFrNkZeLJwrGj_v44a4CxtEPIWUGEqIqGhV594QDi7LDjpwCPGm3FJqYAfCIWaO1Kenc2vM0cEmie5MIcOuSKBPczKKFWuqT6E7FHe8e1OZ8A2Gn3xj69mJtyMzQxj3aZJMZeCMpvt0oVB3XYFpvAlkPzWgAXgziOLAFTmKDD-MkJF7pWSxuZfBSV_lZBX_TdSD2zfA51S1nbk9glE3HPMiOmgNmKJ9WMBleuatLBs6grLU4NI3F5nia9P6KLioM

{
  "username": "e@test.com",
  "password": "test"
}

###
// *** /COMMENT routes *******************

// get all comments - protected route
GET http://localhost:3000/comment
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjI4NDIzMzI5ODAsImV4cCI6MTY2Mjg0MjQxOTM4MH0.isLDz1qqUe7-782pXaNZCX5-NMvl-jXF7DRCHwUJOnhJrAT1F57Cv8AhOYTDoSZe6WQ6wxLPku2iu6nTK5kTNuDVlKanpYgE_zC-_MHoPzGOWVQTwtDd2RCJk2Ly5P9setYo30WYK79bo06ct0eiF0AFcAaTjnFlVwF3aGUp7o9QZlARhT_s3q4Jkl7v7ckqGlakKzgu-DKZubWo8z215O1bdUrAJpOnhhgQu7mMvVuyyRbG-EDtLHSd4Lc68Tc5KCqKKMv4hJkamsbOdbBoElsWDW_Z0XnJF27Vy_XKG_H1uOVIxu0hbm4Tsg8QPTyaFVOd0ctlWi1J_CQM-9oKcXERNLnLO69veTFVTtT57oIHqsPdJO9gJ-S7X6WVNaobnce1LPC5YWO-grLzqjHud9KHLBKPiwL8_MAgQKVHsAb1PwT7n4mWnl8MxjqszWwatKYeC3K1bTohD0xRS1hNVzys23vU2xUZAd4KOus5z_E610M8o-VAYvIsE20esC18pzHvEmtUOVbuXRsm0iNv9R3DU87BXBQyKIL5sawt4P_Ra5C0TAg1xBmU7YL9q3Tvtbxs-lf7f0ImANXSPsBz5XXQIDfAIO06I3KUNPniN0pHDl_d5coFzBplkIRzfigDWFzH3_tHa_XLpTCUudvNFDid58u0QB5Za6SVaCd-Vec

###
// create a new comment - must be logged in
POST http://localhost:3000/comment
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWExNzhhZjE1MWE4ZjgyODdiMmYiLCJpYXQiOjE2NjI4NDg1MDg4MTEsImV4cCI6MTY2Mjg0ODU5NTIxMX0.GvKIOkie0rP7B85lUfSlZAZW_mN5LZlTsNp_DMX6q6lNzomhdpQI19LSWb2mHPfNmjJQU2P31-G5mH-eLkx8ink2C3ksksr7wfaLksZdUSbeeUQXaH5zjiJgCw5Uvn9vNNvyBAWJaFlVLbcdxXAJ5rLa7NHsoXVqrDE5MqOzrJGC8VfyOklx-cAE9-FlmRNFNXrfEb4b0iYqa5v8gQFk9UsbBtUWbq2hNLn-BJMgWwh9cZaafC1P3Fay2Eydaa8EuB1fobpeppbIg0cJT9HS3Y0vqxkw4ygzy0efKCQPvaR8woruDW4VmW7CzVQGjDSmyoFrPDE0iTUFh1A27d6dqwp7X1wCLDYLCYVkTtu5gfI7p4q9O9ZfJWC8cNo223bslungfcVRXuDJG0sO7YDU-_s9Zsbgbu2YiqgqoSoZq3D7kuEopquDEUId2VXMcWR6bvL2Oj2hABLskDZgNz8qT-PzBvOinTxCkrSmcDIgNIJ6HXPJrQ4aoJm0P2E59JyOosoRW5GwRU7LSORvVaM2HZIJSUhaYkJ6D8EDLgdf6dEqg3W2Ykgb2Iu_g5gS9LAanb5Ga3aQdkvjpnfK8_yifw3VfLqzTYHDt-sHYpTfYlr0kUME6LPqKgtnEQ4GEWXb6YCDipbE-Go1bn9vewUjZY7w2pLpt2Lttxqq4CSeFqg

{
  "content": "test comment 7",
  "author": "631d0dc3a387ad2e1a42bf06",
  "post": "63249b5b1c9acd7aca8dfbbb"
}

###
// delete a comment - admin only
DELETE http://localhost:3000/comment/6324d15db47d1a31481503ce
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzFjZWEzYzhhZjE1MWE4ZjgyODdiMzEiLCJpYXQiOjE2NjMzNTI5ODY4MjYsImV4cCI6MTY2MzM1MzA3MzIyNn0.5NGKaPIsB06zCXyof65g55sZkgYDTgAIJQSY8283Dhro_lCM7OQpTuyrwatcfHbqAZ7T4d_STThTtObuHZcw77MeWFX0nsku2oDgtURct1R_4OP5VtsN0oyhpCCeerBYTkqj8ujDA-ksnjRUSDe_VRVoBJYv1PbZfVpsfPTDkCFWoNWRyp55Rp3cUpGkc_lu7HE8FQWggWSVs7KtBPs_anrjVYLdYWptwN3zEZXh5goce39KshNvxRH2IdLegIHBffJufmPqQR5yD6X9qMEeq4PJhQ7NYfyhcYbH9xkniZrb9CQ3A3LhpCnoUq_vArOe871grtXfWGuoPm_bEKKxPoXHjM2Bj1wJl6u59Fe5Lh2WUohr_VJqr8-T9WzdPC0lNiAJIaWO_m-pJD8qbV9DMKCiYH2o3MOkEZpzCWW-49ZAWp_a9tEK3clyECkQumuusi5Z5i6mEJxpsGs1dhbnFLR621VteDCA-ij_-WIBvOhzX3FGLi2p2LJ0_ZebI_xEUSjaREibntauUotwxDI5Woav6sI5QC9ckqkCrEkmv6H94FoYW0uKI6JKnUdsB-EJJDuN9GaYTyowbsbJC4kn4yH0hao8jpjQheRtQumXqJ7KvKFFBWYVhV9zV8wXutfuxwkDfJ79IGMjbOrVm0TcKOfO9s1QizIQvCnll2G-k_U

### 
// *** /LOGIN routes *******************
POST http://localhost:3000/login
content-type: application/json

{
  "username": "a@test,com",
  "password": "test"
}